name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # Use the latest stable version of Flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href="/portfolio/"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --single-branch --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r build/web/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy Flutter Web App to GitHub Pages"
          git push --force origin gh-pages
